
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA FLOAT LABEL LBRACKET MEMORY MNEMONIC NEWLINE NUMBER RBRACKET REGISTER SECTIONprogram : line\n                | program lineline : LABEL COLON NEWLINEline : LABEL COLON FLOATline : LABEL COLON NUMBERline : SECTIONline : instruction NEWLINE\n                | instructionline : NEWLINEinstruction : MNEMONIC REGISTER COMMA REGISTERinstruction : MNEMONIC REGISTER COMMA NUMBERinstruction : MNEMONIC REGISTER COMMA MEMORYinstruction : MNEMONIC REGISTER COMMA LBRACKET REGISTER RBRACKETinstruction : MNEMONIC MEMORY COMMA REGISTERinstruction : MNEMONIC MEMORY COMMA NUMBERinstruction : MNEMONIC LBRACKET REGISTER RBRACKET COMMA REGISTERinstruction : MNEMONIC MEMORYinstruction : MNEMONIC REGISTERinstruction : MNEMONIC NUMBERinstruction : MNEMONIC LABELinstruction : MNEMONIC'
    
_lr_action_items = {'LABEL':([0,1,2,4,5,6,7,8,10,11,12,13,15,16,17,18,22,23,24,26,27,31,32,],[3,3,-1,-9,-6,-8,15,-2,-7,-18,-19,-17,-20,-3,-4,-5,-10,-11,-12,-14,-15,-13,-16,]),'SECTION':([0,1,2,4,5,6,7,8,10,11,12,13,15,16,17,18,22,23,24,26,27,31,32,],[5,5,-1,-9,-6,-8,-21,-2,-7,-18,-19,-17,-20,-3,-4,-5,-10,-11,-12,-14,-15,-13,-16,]),'NEWLINE':([0,1,2,4,5,6,7,8,9,10,11,12,13,15,16,17,18,22,23,24,26,27,31,32,],[4,4,-1,-9,-6,10,-21,-2,16,-7,-18,-19,-17,-20,-3,-4,-5,-10,-11,-12,-14,-15,-13,-16,]),'MNEMONIC':([0,1,2,4,5,6,7,8,10,11,12,13,15,16,17,18,22,23,24,26,27,31,32,],[7,7,-1,-9,-6,-8,-21,-2,-7,-18,-19,-17,-20,-3,-4,-5,-10,-11,-12,-14,-15,-13,-16,]),'$end':([1,2,4,5,6,7,8,10,11,12,13,15,16,17,18,22,23,24,26,27,31,32,],[0,-1,-9,-6,-8,-21,-2,-7,-18,-19,-17,-20,-3,-4,-5,-10,-11,-12,-14,-15,-13,-16,]),'COLON':([3,],[9,]),'REGISTER':([7,14,19,20,25,30,],[11,21,22,26,29,32,]),'MEMORY':([7,19,],[13,24,]),'LBRACKET':([7,19,],[14,25,]),'NUMBER':([7,9,19,20,],[12,18,23,27,]),'FLOAT':([9,],[17,]),'COMMA':([11,13,28,],[19,20,30,]),'RBRACKET':([21,29,],[28,31,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'line':([0,1,],[2,8,]),'instruction':([0,1,],[6,6,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> line','program',1,'p_program','asm_parser.py',22),
  ('program -> program line','program',2,'p_program','asm_parser.py',23),
  ('line -> LABEL COLON NEWLINE','line',3,'p_line_label','asm_parser.py',26),
  ('line -> LABEL COLON FLOAT','line',3,'p_line_variable_float','asm_parser.py',33),
  ('line -> LABEL COLON NUMBER','line',3,'p_line_variable_number','asm_parser.py',39),
  ('line -> SECTION','line',1,'p_line_section','asm_parser.py',44),
  ('line -> instruction NEWLINE','line',2,'p_line_instr','asm_parser.py',49),
  ('line -> instruction','line',1,'p_line_instr','asm_parser.py',50),
  ('line -> NEWLINE','line',1,'p_line_empty','asm_parser.py',55),
  ('instruction -> MNEMONIC REGISTER COMMA REGISTER','instruction',4,'p_instr_reg_reg','asm_parser.py',58),
  ('instruction -> MNEMONIC REGISTER COMMA NUMBER','instruction',4,'p_instr_reg_imm','asm_parser.py',65),
  ('instruction -> MNEMONIC REGISTER COMMA MEMORY','instruction',4,'p_instr_reg_mem','asm_parser.py',74),
  ('instruction -> MNEMONIC REGISTER COMMA LBRACKET REGISTER RBRACKET','instruction',6,'p_instr_reg_ind','asm_parser.py',83),
  ('instruction -> MNEMONIC MEMORY COMMA REGISTER','instruction',4,'p_instr_mem_reg','asm_parser.py',90),
  ('instruction -> MNEMONIC MEMORY COMMA NUMBER','instruction',4,'p_instr_mem_inm','asm_parser.py',99),
  ('instruction -> MNEMONIC LBRACKET REGISTER RBRACKET COMMA REGISTER','instruction',6,'p_instr_ind_reg','asm_parser.py',108),
  ('instruction -> MNEMONIC MEMORY','instruction',2,'p_instr_mem','asm_parser.py',117),
  ('instruction -> MNEMONIC REGISTER','instruction',2,'p_instr_reg','asm_parser.py',126),
  ('instruction -> MNEMONIC NUMBER','instruction',2,'p_instr_inm','asm_parser.py',135),
  ('instruction -> MNEMONIC LABEL','instruction',2,'p_instr_label','asm_parser.py',144),
  ('instruction -> MNEMONIC','instruction',1,'p_instr_single','asm_parser.py',159),
]
