
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA FLOAT LABEL LBRACKET MEMORY MNEMONIC NEWLINE NUMBER QUOTE RBRACKET REFERENCE REGISTER SECTION STR VARprogram : line\n| program lineline : LABEL COLON NEWLINEline : VAR COLON FLOAT NEWLINEline : VAR COLON NUMBER NEWLINEline : VAR COLON STRline : SECTIONline : SECTION REFERENCE\n| SECTION VAR\n| SECTION LABELline : instruction NEWLINE\n| instructionline : NEWLINEinstruction : MNEMONIC REGISTER COMMA REGISTERinstruction : MNEMONIC REGISTER COMMA NUMBERinstruction : MNEMONIC REGISTER COMMA MEMORYinstruction : MNEMONIC REGISTER COMMA LBRACKET VAR RBRACKETinstruction : MNEMONIC REGISTER COMMA LBRACKET REGISTER RBRACKETinstruction : MNEMONIC MEMORY COMMA REGISTERinstruction : MNEMONIC LBRACKET VAR RBRACKET COMMA REGISTERinstruction : MNEMONIC MEMORY COMMA NUMBERinstruction : MNEMONIC LBRACKET VAR RBRACKET COMMA NUMBERinstruction : MNEMONIC LBRACKET REGISTER RBRACKET COMMA REGISTERinstruction : MNEMONIC MEMORYinstruction : MNEMONIC REGISTERinstruction : MNEMONIC NUMBERinstruction : MNEMONIC LABEL\n| MNEMONIC VARinstruction : MNEMONIC'
    
_lr_action_items = {'LABEL':([0,1,2,4,6,7,8,9,12,13,14,15,16,17,18,20,21,22,25,30,31,32,33,34,36,37,44,45,46,47,48,],[3,3,-1,-13,14,-12,21,-2,-8,-9,-10,-11,-25,-26,-24,-28,-27,-3,-6,-4,-5,-14,-15,-16,-19,-21,-18,-17,-20,-22,-23,]),'VAR':([0,1,2,4,6,7,8,9,12,13,14,15,16,17,18,19,20,21,22,25,30,31,32,33,34,35,36,37,44,45,46,47,48,],[5,5,-1,-13,13,-12,20,-2,-8,-9,-10,-11,-25,-26,-24,28,-28,-27,-3,-6,-4,-5,-14,-15,-16,41,-19,-21,-18,-17,-20,-22,-23,]),'SECTION':([0,1,2,4,6,7,8,9,12,13,14,15,16,17,18,20,21,22,25,30,31,32,33,34,36,37,44,45,46,47,48,],[6,6,-1,-13,-7,-12,-29,-2,-8,-9,-10,-11,-25,-26,-24,-28,-27,-3,-6,-4,-5,-14,-15,-16,-19,-21,-18,-17,-20,-22,-23,]),'NEWLINE':([0,1,2,4,6,7,8,9,10,12,13,14,15,16,17,18,20,21,22,23,24,25,30,31,32,33,34,36,37,44,45,46,47,48,],[4,4,-1,-13,-7,15,-29,-2,22,-8,-9,-10,-11,-25,-26,-24,-28,-27,-3,30,31,-6,-4,-5,-14,-15,-16,-19,-21,-18,-17,-20,-22,-23,]),'MNEMONIC':([0,1,2,4,6,7,8,9,12,13,14,15,16,17,18,20,21,22,25,30,31,32,33,34,36,37,44,45,46,47,48,],[8,8,-1,-13,-7,-12,-29,-2,-8,-9,-10,-11,-25,-26,-24,-28,-27,-3,-6,-4,-5,-14,-15,-16,-19,-21,-18,-17,-20,-22,-23,]),'$end':([1,2,4,6,7,8,9,12,13,14,15,16,17,18,20,21,22,25,30,31,32,33,34,36,37,44,45,46,47,48,],[0,-1,-13,-7,-12,-29,-2,-8,-9,-10,-11,-25,-26,-24,-28,-27,-3,-6,-4,-5,-14,-15,-16,-19,-21,-18,-17,-20,-22,-23,]),'COLON':([3,5,],[10,11,]),'REFERENCE':([6,],[12,]),'REGISTER':([8,19,26,27,35,42,43,],[16,29,32,36,40,46,48,]),'MEMORY':([8,26,],[18,34,]),'LBRACKET':([8,26,],[19,35,]),'NUMBER':([8,11,26,27,42,],[17,24,33,37,47,]),'FLOAT':([11,],[23,]),'STR':([11,],[25,]),'COMMA':([16,18,38,39,],[26,27,42,43,]),'RBRACKET':([28,29,40,41,],[38,39,44,45,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'line':([0,1,],[2,9,]),'instruction':([0,1,],[7,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> line','program',1,'p_program','asm_parser.py',28),
  ('program -> program line','program',2,'p_program','asm_parser.py',29),
  ('line -> LABEL COLON NEWLINE','line',3,'p_line_label','asm_parser.py',32),
  ('line -> VAR COLON FLOAT NEWLINE','line',4,'p_line_variable_float','asm_parser.py',39),
  ('line -> VAR COLON NUMBER NEWLINE','line',4,'p_line_variable_number','asm_parser.py',47),
  ('line -> VAR COLON STR','line',3,'p_line_variable_char','asm_parser.py',54),
  ('line -> SECTION','line',1,'p_line_section','asm_parser.py',61),
  ('line -> SECTION REFERENCE','line',2,'p_line_import','asm_parser.py',66),
  ('line -> SECTION VAR','line',2,'p_line_import','asm_parser.py',67),
  ('line -> SECTION LABEL','line',2,'p_line_import','asm_parser.py',68),
  ('line -> instruction NEWLINE','line',2,'p_line_instr','asm_parser.py',74),
  ('line -> instruction','line',1,'p_line_instr','asm_parser.py',75),
  ('line -> NEWLINE','line',1,'p_line_empty','asm_parser.py',80),
  ('instruction -> MNEMONIC REGISTER COMMA REGISTER','instruction',4,'p_instr_reg_reg','asm_parser.py',83),
  ('instruction -> MNEMONIC REGISTER COMMA NUMBER','instruction',4,'p_instr_reg_imm','asm_parser.py',92),
  ('instruction -> MNEMONIC REGISTER COMMA MEMORY','instruction',4,'p_instr_reg_mem','asm_parser.py',103),
  ('instruction -> MNEMONIC REGISTER COMMA LBRACKET VAR RBRACKET','instruction',6,'p_instr_reg_var','asm_parser.py',114),
  ('instruction -> MNEMONIC REGISTER COMMA LBRACKET REGISTER RBRACKET','instruction',6,'p_instr_reg_ind','asm_parser.py',125),
  ('instruction -> MNEMONIC MEMORY COMMA REGISTER','instruction',4,'p_instr_mem_reg','asm_parser.py',134),
  ('instruction -> MNEMONIC LBRACKET VAR RBRACKET COMMA REGISTER','instruction',6,'p_instr_var_reg','asm_parser.py',145),
  ('instruction -> MNEMONIC MEMORY COMMA NUMBER','instruction',4,'p_instr_mem_inm','asm_parser.py',158),
  ('instruction -> MNEMONIC LBRACKET VAR RBRACKET COMMA NUMBER','instruction',6,'p_instr_var_inm','asm_parser.py',169),
  ('instruction -> MNEMONIC LBRACKET REGISTER RBRACKET COMMA REGISTER','instruction',6,'p_instr_ind_reg','asm_parser.py',182),
  ('instruction -> MNEMONIC MEMORY','instruction',2,'p_instr_mem','asm_parser.py',193),
  ('instruction -> MNEMONIC REGISTER','instruction',2,'p_instr_reg','asm_parser.py',204),
  ('instruction -> MNEMONIC NUMBER','instruction',2,'p_instr_inm','asm_parser.py',215),
  ('instruction -> MNEMONIC LABEL','instruction',2,'p_instr_label','asm_parser.py',226),
  ('instruction -> MNEMONIC VAR','instruction',2,'p_instr_label','asm_parser.py',227),
  ('instruction -> MNEMONIC','instruction',1,'p_instr_single','asm_parser.py',245),
]
