
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA FLOAT LABEL LBRACKET MEMORY MNEMONIC NEWLINE NUMBER RBRACKET REFERENCE REGISTER SECTION VARprogram : line\n                | program lineline : LABEL COLON NEWLINEline : VAR COLON FLOAT NEWLINEline : VAR COLON NUMBER NEWLINEline : SECTIONline : SECTION REFERENCE\n                | SECTION VARline : instruction NEWLINE\n                | instructionline : NEWLINEinstruction : MNEMONIC REGISTER COMMA REGISTERinstruction : MNEMONIC REGISTER COMMA NUMBERinstruction : MNEMONIC REGISTER COMMA MEMORYinstruction : MNEMONIC REGISTER COMMA LBRACKET VAR RBRACKETinstruction : MNEMONIC REGISTER COMMA LBRACKET REGISTER RBRACKETinstruction : MNEMONIC MEMORY COMMA REGISTERinstruction : MNEMONIC LBRACKET VAR RBRACKET COMMA REGISTERinstruction : MNEMONIC MEMORY COMMA NUMBERinstruction : MNEMONIC LBRACKET VAR RBRACKET COMMA NUMBERinstruction : MNEMONIC LBRACKET REGISTER RBRACKET COMMA REGISTERinstruction : MNEMONIC MEMORYinstruction : MNEMONIC REGISTERinstruction : MNEMONIC NUMBERinstruction : MNEMONIC LABEL\n                        | MNEMONIC VARinstruction : MNEMONIC'
    
_lr_action_items = {'LABEL':([0,1,2,4,6,7,8,9,12,13,14,15,16,17,19,20,21,28,29,30,31,32,34,35,42,43,44,45,46,],[3,3,-1,-11,-6,-10,20,-2,-7,-8,-9,-23,-24,-22,-26,-25,-3,-4,-5,-12,-13,-14,-17,-19,-16,-15,-18,-20,-21,]),'VAR':([0,1,2,4,6,7,8,9,12,13,14,15,16,17,18,19,20,21,28,29,30,31,32,33,34,35,42,43,44,45,46,],[5,5,-1,-11,13,-10,19,-2,-7,-8,-9,-23,-24,-22,26,-26,-25,-3,-4,-5,-12,-13,-14,39,-17,-19,-16,-15,-18,-20,-21,]),'SECTION':([0,1,2,4,6,7,8,9,12,13,14,15,16,17,19,20,21,28,29,30,31,32,34,35,42,43,44,45,46,],[6,6,-1,-11,-6,-10,-27,-2,-7,-8,-9,-23,-24,-22,-26,-25,-3,-4,-5,-12,-13,-14,-17,-19,-16,-15,-18,-20,-21,]),'NEWLINE':([0,1,2,4,6,7,8,9,10,12,13,14,15,16,17,19,20,21,22,23,28,29,30,31,32,34,35,42,43,44,45,46,],[4,4,-1,-11,-6,14,-27,-2,21,-7,-8,-9,-23,-24,-22,-26,-25,-3,28,29,-4,-5,-12,-13,-14,-17,-19,-16,-15,-18,-20,-21,]),'MNEMONIC':([0,1,2,4,6,7,8,9,12,13,14,15,16,17,19,20,21,28,29,30,31,32,34,35,42,43,44,45,46,],[8,8,-1,-11,-6,-10,-27,-2,-7,-8,-9,-23,-24,-22,-26,-25,-3,-4,-5,-12,-13,-14,-17,-19,-16,-15,-18,-20,-21,]),'$end':([1,2,4,6,7,8,9,12,13,14,15,16,17,19,20,21,28,29,30,31,32,34,35,42,43,44,45,46,],[0,-1,-11,-6,-10,-27,-2,-7,-8,-9,-23,-24,-22,-26,-25,-3,-4,-5,-12,-13,-14,-17,-19,-16,-15,-18,-20,-21,]),'COLON':([3,5,],[10,11,]),'REFERENCE':([6,],[12,]),'REGISTER':([8,18,24,25,33,40,41,],[15,27,30,34,38,44,46,]),'MEMORY':([8,24,],[17,32,]),'LBRACKET':([8,24,],[18,33,]),'NUMBER':([8,11,24,25,40,],[16,23,31,35,45,]),'FLOAT':([11,],[22,]),'COMMA':([15,17,36,37,],[24,25,40,41,]),'RBRACKET':([26,27,38,39,],[36,37,42,43,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'line':([0,1,],[2,9,]),'instruction':([0,1,],[7,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> line','program',1,'p_program','asm_parser.py',23),
  ('program -> program line','program',2,'p_program','asm_parser.py',24),
  ('line -> LABEL COLON NEWLINE','line',3,'p_line_label','asm_parser.py',27),
  ('line -> VAR COLON FLOAT NEWLINE','line',4,'p_line_variable_float','asm_parser.py',34),
  ('line -> VAR COLON NUMBER NEWLINE','line',4,'p_line_variable_number','asm_parser.py',42),
  ('line -> SECTION','line',1,'p_line_section','asm_parser.py',49),
  ('line -> SECTION REFERENCE','line',2,'p_line_import','asm_parser.py',54),
  ('line -> SECTION VAR','line',2,'p_line_import','asm_parser.py',55),
  ('line -> instruction NEWLINE','line',2,'p_line_instr','asm_parser.py',61),
  ('line -> instruction','line',1,'p_line_instr','asm_parser.py',62),
  ('line -> NEWLINE','line',1,'p_line_empty','asm_parser.py',67),
  ('instruction -> MNEMONIC REGISTER COMMA REGISTER','instruction',4,'p_instr_reg_reg','asm_parser.py',70),
  ('instruction -> MNEMONIC REGISTER COMMA NUMBER','instruction',4,'p_instr_reg_imm','asm_parser.py',77),
  ('instruction -> MNEMONIC REGISTER COMMA MEMORY','instruction',4,'p_instr_reg_mem','asm_parser.py',86),
  ('instruction -> MNEMONIC REGISTER COMMA LBRACKET VAR RBRACKET','instruction',6,'p_instr_reg_var','asm_parser.py',95),
  ('instruction -> MNEMONIC REGISTER COMMA LBRACKET REGISTER RBRACKET','instruction',6,'p_instr_reg_ind','asm_parser.py',104),
  ('instruction -> MNEMONIC MEMORY COMMA REGISTER','instruction',4,'p_instr_mem_reg','asm_parser.py',111),
  ('instruction -> MNEMONIC LBRACKET VAR RBRACKET COMMA REGISTER','instruction',6,'p_instr_var_reg','asm_parser.py',120),
  ('instruction -> MNEMONIC MEMORY COMMA NUMBER','instruction',4,'p_instr_mem_inm','asm_parser.py',131),
  ('instruction -> MNEMONIC LBRACKET VAR RBRACKET COMMA NUMBER','instruction',6,'p_instr_var_inm','asm_parser.py',140),
  ('instruction -> MNEMONIC LBRACKET REGISTER RBRACKET COMMA REGISTER','instruction',6,'p_instr_ind_reg','asm_parser.py',151),
  ('instruction -> MNEMONIC MEMORY','instruction',2,'p_instr_mem','asm_parser.py',160),
  ('instruction -> MNEMONIC REGISTER','instruction',2,'p_instr_reg','asm_parser.py',169),
  ('instruction -> MNEMONIC NUMBER','instruction',2,'p_instr_inm','asm_parser.py',178),
  ('instruction -> MNEMONIC LABEL','instruction',2,'p_instr_label','asm_parser.py',187),
  ('instruction -> MNEMONIC VAR','instruction',2,'p_instr_label','asm_parser.py',188),
  ('instruction -> MNEMONIC','instruction',1,'p_instr_single','asm_parser.py',204),
]
