def get_methods_map(cu):
    """
    Recibe 'cu' (una instancia de ControlUnit) y retorna el diccionario.
    """
    return {
            # Control
            "nop_": lambda x, y: cu.nop(),
            "hlt_": lambda x, y: cu.hlt(),
            "ret_": lambda x, y: cu.ret(),
            "ei_": lambda x, y: cu.ei(),
            "di_": lambda x, y: cu.di(),
            "iret_": lambda x, y: cu.iret(),
            "push_r": lambda x, y: cu.push(x),
            "pop_r": lambda x, y: cu.pop(x),
            "int_i": lambda x, y: cu.int(),
            
            # MOV
            "movb_rr": lambda x, y: cu.mov_ra(x, y, 8),
            "movb_ri": lambda x, y: cu.mov_ra(x, y, 8),
            "movb_rm": lambda x, y: cu.mov_rm(x, y, 8),
            "movb_rn": lambda x, y: cu.mov_ra(x, y, 8),
            "movb_mr": lambda x, y: cu.mov_ma(x, y, 8),
            "movb_mi": lambda x, y: cu.mov_ma(x, y, 8),
            "movb_nr": lambda x, y: cu.mov_ra(x, y, 8),
            "movh_rr": lambda x, y: cu.mov_ra(x, y, 16),
            "movh_ri": lambda x, y: cu.mov_ra(x, y, 16),
            "movh_rm": lambda x, y: cu.mov_rm(x, y, 16),
            "movh_rn": lambda x, y: cu.mov_ra(x, y, 16),
            "movh_mr": lambda x, y: cu.mov_ma(x, y, 16),
            "movh_mi": lambda x, y: cu.mov_ma(x, y, 16),
            "movh_nr": lambda x, y: cu.mov_ra(x, y, 16),
            "movw_rr": lambda x, y: cu.mov_ra(x, y, 32),
            "movw_ri": lambda x, y: cu.mov_ra(x, y, 32),
            "movw_rm": lambda x, y: cu.mov_rm(x, y, 32),
            "movw_rn": lambda x, y: cu.mov_ra(x, y, 32),
            "movw_mr": lambda x, y: cu.mov_ma(x, y, 32),
            "movw_mi": lambda x, y: cu.mov_ma(x, y, 32),
            "movw_nr": lambda x, y: cu.mov_ra(x, y, 32),
            "movd_rr": lambda x, y: cu.mov_ra(x, y, 64),
            "movd_ri": lambda x, y: cu.mov_ra(x, y, 64),
            "movd_rm": lambda x, y: cu.mov_rm(x, y, 64),
            "movd_rn": lambda x, y: cu.mov_ra(x, y, 64),
            "movd_mr": lambda x, y: cu.mov_ma(x, y, 64),
            "movd_mi": lambda x, y: cu.mov_ma(x, y, 64),
            "movd_nr": lambda x, y: cu.mov_ra(x, y, 64),
            "swap_r": lambda x, y: cu.swap_r(x),
            "swap_rr": lambda x, y: cu.swap_rr(x, y),
            
            # LOAD
            "loadb_m": lambda x, y: cu.load_m(x, 8),
            "loadb_i": lambda x, y: cu.load_i(x, 8),
            "loadb_rm": lambda x, y: cu.load_rm(x, y, 8),
            "loadb_ri": lambda x, y: cu.load_ri(x, y, 8),
            "loadh_m": lambda x, y: cu.load_m(x, 16),
            "loadh_i": lambda x, y: cu.load_i(x, 16),
            "loadh_rm": lambda x, y: cu.load_rm(x, y, 16),
            "loadh_ri": lambda x, y: cu.load_ri(x, y, 16),
            "loadw_m": lambda x, y: cu.load_m(x, 32),
            "loadw_i": lambda x, y: cu.load_i(x, 32),
            "loadw_rm": lambda x, y: cu.load_rm(x, y, 32),
            "loadw_ri": lambda x, y: cu.load_ri(x, y, 32),
            "loadd_m": lambda x, y: cu.load_m(x, 64),
            "loadd_i": lambda x, y: cu.load_i(x, 64),
            "loadd_rm": lambda x, y: cu.load_rm(x, y, 64),
            "loadd_ri": lambda x, y: cu.load_ri(x, y, 64),
            "lea_m": lambda x, y: cu.lea_m(x),
            "lea_rm": lambda x, y: cu.lea_rm(x, y),
            
            # STORE
            "storeb_m": lambda x, y: cu.store_m(x, 8),
            "storeb_r": lambda x, y: cu.store_r(x, 8),
            "storeb_mr": lambda x, y: cu.store_ma(x, y, 8),
            "storeb_mi": lambda x, y: cu.store_ma(x, y, 8),
            "storeh_m": lambda x, y: cu.store_m(x, 16),
            "storeh_r": lambda x, y: cu.store_r(x, 16),
            "storeh_mr": lambda x, y: cu.store_ma(x, y, 16),
            "storeh_mi": lambda x, y: cu.store_ma(x, y, 16),
            "storew_m": lambda x, y: cu.store_m(x, 32),
            "storew_r": lambda x, y: cu.store_r(x, 32),
            "storew_mr": lambda x, y: cu.store_ma(x, y, 32),
            "storew_mi": lambda x, y: cu.store_ma(x, y, 32),
            "stored_m": lambda x, y: cu.store_m(x, 64),
            "stored_r": lambda x, y: cu.store_r(x, 64),
            "stored_mr": lambda x, y: cu.store_ma(x, y, 64),
            "stored_mi": lambda x, y: cu.store_ma(x, y, 64),
            
            # SEXT
            "sext_ri": lambda x, y: cu.sext(),
            
            # Aritmética
            "add_m": lambda x, y: cu.add_m(x),
            "add_r": lambda x, y: cu.add_a(x),
            "add_i": lambda x, y: cu.add_a(x),
            "add_rr": lambda x, y: cu.add_ra(x, y),
            "add_ri": lambda x, y: cu.add_ra(x, y),
            "add_rm": lambda x, y: cu.add_rm(x, y),
            "add_rn": lambda x, y: cu.add_ra(x, y),
            "sub_m": lambda x, y: cu.sub_m(x),
            "sub_r": lambda x, y: cu.sub_a(x),
            "sub_i": lambda x, y: cu.sub_a(x),
            "sub_rr": lambda x, y: cu.sub_ra(x, y),
            "sub_ri": lambda x, y: cu.sub_ra(x, y),
            "sub_rm": lambda x, y: cu.sub_rm(x, y),
            "sub_rn": lambda x, y: cu.sub_ra(x, y),
            "mul_m": lambda x, y: cu.mul_m(x),
            "mul_r": lambda x, y: cu.mul_a(x),
            "mul_i": lambda x, y: cu.mul_a(x),
            "mul_rr": lambda x, y: cu.mul_ra(x, y),
            "mul_ri": lambda x, y: cu.mul_ra(x, y),
            "mul_rm": lambda x, y: cu.mul_rm(x, y),
            "mul_rn": lambda x, y: cu.mul_ra(x, y),
            "div_m": lambda x, y: cu.div_m(x),
            "div_r": lambda x, y: cu.div_a(x),
            "div_i": lambda x, y: cu.div_a(x),
            "div_rr": lambda x, y: cu.div_ra(x, y),
            "div_ri": lambda x, y: cu.div_ra(x, y),
            "div_rm": lambda x, y: cu.div_rm(x, y),
            "div_rn": lambda x, y: cu.div_ra(x, y),
            "inc_r": lambda x, y: cu.inc_r(x),
            "inc_m": lambda x, y: cu.inc_m(x),
            "dec_r": lambda x, y: cu.dec_r(x),
            "dec_m": lambda x, y: cu.dec_m(x),
            "neg_r": lambda x, y: cu.neg(),
            "neg_m": lambda x, y: cu.neg(),
            
            # Lógica
            "and_m": lambda x, y: cu.and_m(x),
            "and_r": lambda x, y: cu.and_a(x),
            "and_i": lambda x, y: cu.and_a(x),
            "and_rr": lambda x, y: cu.and_ra(x, y),
            "and_ri": lambda x, y: cu.and_ra(x, y),
            "and_rm": lambda x, y: cu.and_rm(x, y),
            "and_rn": lambda x, y: cu.and_ra(x, y),
            "or_m": lambda x, y: cu.or_m(x),
            "or_r": lambda x, y: cu.or_a(x),
            "or_i": lambda x, y: cu.or_a(x),
            "or_rr": lambda x, y: cu.or_ra(x, y),
            "or_ri": lambda x, y: cu.or_ra(x, y),
            "or_rm": lambda x, y: cu.or_rm(x, y),
            "or_rn": lambda x, y: cu.or_ra(x, y),
            "xor_m": lambda x, y: cu.xor_m(x),
            "xor_r": lambda x, y: cu.xor_a(x),
            "xor_i": lambda x, y: cu.xor_a(x),
            "xor_rr": lambda x, y: cu.xor_ra(x, y),
            "xor_ri": lambda x, y: cu.xor_ra(x, y),
            "xor_rm": lambda x, y: cu.xor_rm(x, y),
            "xor_rn": lambda x, y: cu.xor_ra(x, y),
            "not_r": lambda x, y: cu.not_r(x),
            "not_m": lambda x, y: cu.not_m(x),
            
            # Otras ALU
            "cmp_m": lambda x, y: cu.cmp_m(x),
            "cmp_r": lambda x, y: cu.cmp_a(x),
            "cmp_i": lambda x, y: cu.cmp_a(x),
            "cmp_rr": lambda x, y: cu.cmp_ra(x, y),
            "cmp_ri": lambda x, y: cu.cmp_ra(x, y),
            "cmp_rm": lambda x, y: cu.cmp_rm(x, y),
            "cmp_rn": lambda x, y: cu.cmp_ra(x, y),
            "test_m": lambda x, y: cu.test_m(x),
            "test_r": lambda x, y: cu.test_a(x),
            "test_i": lambda x, y: cu.test_a(x),
            "test_rr": lambda x, y: cu.test_ra(x, y),
            "test_ri": lambda x, y: cu.test_ra(x, y),
            "test_rm": lambda x, y: cu.test_rm(x, y),
            "test_rn": lambda x, y: cu.test_ra(x, y),
            "shl_i": lambda x, y: cu.shl_i(x),
            "shl_ri": lambda x, y: cu.shl_ri(x, y),
            "shr_i": lambda x, y: cu.shr_i(x),
            "shr_ri": lambda x, y: cu.shr_ri(x, y),
            "rol_i": lambda x, y: cu.ror_i(x),
            "rol_ri": lambda x, y: cu.ror_ri(x, y),
            "ror_i": lambda x, y: cu.ror_i(x),
            "ror_ri": lambda x, y: cu.ror_ri(x, y),
            "cmpz_r": lambda x, y: cu.cmpz_r(x),
            "cmpz_m": lambda x, y: cu.cmpz_m(x),
            
            # Saltos
            "jmp_m": lambda x, y: cu.jmp(x),
            "jz_m": lambda x, y: cu.j_condicional(x, 'z'),
            "jnz_m": lambda x, y: cu.jn_condicional(x, 'z'),
            "jc_m": lambda x, y: cu.j_condicional(x, 'c'),
            "jnc_m": lambda x, y: cu.jn_condicional(x, 'c'),
            "js_m": lambda x, y: cu.j_condicional(x, 's'),
            "jns_m": lambda x, y: cu.jn_condicional(x, 's'),
            "jo_m": lambda x, y: cu.j_condicional(x, 'v'),
            "jno_m": lambda x, y: cu.jn_condicional(x, 'v'),
            "jl_m": lambda x, y: cu.j_comparacion(x, 's', 'v', '<'),
            "jg_m": lambda x, y: cu.j_comparacion(x, 's', 'v', '>'),
            "jge_m": lambda x, y: cu.j_comparacion(x, 's', 'v', '>='),
            "jle_m": lambda x, y: cu.j_comparacion(x, 's', 'v', '<='),
            "call_m": lambda x, y: cu.call_m(x),
        }